# Welcome to Jekyll!
#
# This config file is meant for settings that affect the whole site, values
# which you are expected to set up once and rarely edit after that.

# Site settings
title: DHAP 2019
description: >- # this means to ignore newlines until "baseurl:"
  This will show up in Google Search results.
  Lorem ipsum dolor sit amet, consectetur adipisicing elit. 
  Atque, odit. Omnis adipisci laborum, quasi iste doloribus?
  Dolore neque amet inventore!
baseurl: "" # the subpath of your site root, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
facebook_url: https://www.facebook.com/dhaseanplus2018/
instagram_url: https://www.instagram.com/dhaseanplus/

# Build settings
markdown: kramdown

# colors used throughout the site
colors:
  base1: "#002266"
  base2: "#4D6599"
  base3: "#E7FBFF"
  accent1: "#F79E76"
  accent2: "#C73B1F"

# dhap dates (formatted YYYY-MM-DD[Thh:mm])
# launch_time: when the website will be deployed
# start_time: when the summit starts
# end_time: when the summit ends
dates:
  launch_time: 2019-01-25T00:00
  start_time: 2019-06-06T00:00
  end_time: 2019-06-03T19:00

collections_dir: writeups

collections: 
  councils:
    output: true
  org_committees:
    output: true
  people:
    output: false

defaults: 
  - scope: 
      path: ""
      type: councils
    values:
      layout: group
  - scope: 
      path: ""
      type: org_committees
    values:
      layout: group

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
